<template>
    <div>
        <vs-header></vs-header>
        <vs-section :data="community.brand"></vs-section>
        <vs-footer></vs-footer>
        <vs-back-top></vs-back-top>
    </div>
</template>

<script>
import VsHeader from "../components/community/VsHeader"
import VsFooter from "../components/index/VsFooter"
import VsSection from "../components/community/VsSection"
import VsBackTop from "../components/CBA/VsBackTop"

import indexApis from "../apis/indexApis"
export default {
    components:{
        VsHeader,
        VsFooter,
        VsSection,
        VsBackTop
    },
    data(){
        return{
            community:{}
        }
    },
    beforeCreate(){
        indexApis.getCommunityData(data=>{
            this.community=data;
        })
    },
    watch:{
        community:{
            handler(n,o){
                //console.log(n)
            },
            deep:true
        }
    },
    methods:{
        // 初始化页面
        _initData(){
            indexApis.getCommunityData(data=>{
                console.log(data)
                this.community=data;
            })
        }
    }
    // ,data(){
    //     return{
    //         brand:[
    //             {
    //                 brandTitle:"NBA论坛",
    //                 brandRow:[
    //                     {
    //                         brandRowTitle:"主版",
    //                         brandRowTag:[
    //                             {
    //                                 tag:"湿乎乎的话题",
    //                                 tiezi:"18896贴"
    //                             },
    //                             {
    //                                 tag:"篮球场",
    //                                 tiezi:"489贴"
    //                             },
    //                             {
    //                                 tag:"路人王专区",
    //                                 tiezi:"188贴"
    //                             },
    //                             {
    //                                 tag:"天天NBA",
    //                                 tiezi:"18贴"
    //                             }
    //                         ]
    //                     },
    //                     {
    //                         brandRowTitle:"球队分区",
    //                         brandRowTag:[
    //                             {
    //                                 tag:"火箭专区",
    //                                 tiezi:"3317贴"
    //                             },
    //                             {
    //                                 tag:"湖人专区",
    //                                 tiezi:"2256贴"
    //                             },
    //                             {
    //                                 tag:"勇士专区",
    //                                 tiezi:"2357贴"
    //                             },
    //                             {
    //                                 tag:"马刺专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"凯尔特人区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"雷霆专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"骑士专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"76人专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"森林狼专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"猛龙专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"独行侠专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"快船专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"尼克斯专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"公牛专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"篮网专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"步行者专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"开拓者专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"热火专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"奇才专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"爵士专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"灰熊专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"太阳专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"国王专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"鹈鹕专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"雄鹿专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"掘金专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"老鹰专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"活塞专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"魔术专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"黄蜂专区",
    //                                 tiezi:"555贴"
    //                             }
    //                         ]
    //                     },
    //                     {
    //                         brandRowTitle:"更多",
    //                         brandRowTag:[
    //                             {
    //                                 tag:"路人王动态",
    //                                 tiezi:"14贴"
    //                             },
    //                             {
    //                                 tag:"林书豪专区",
    //                                 tiezi:"48贴"
    //                             },
    //                             {
    //                                 tag:"NBA2KOL2",
    //                                 tiezi:"18贴"
    //                             },
    //                             {
    //                                 tag:"NBA选秀-NCAA",
    //                                 tiezi:""
    //                             },
    //                             {
    //                                 tag:"深篮讨论区",
    //                                 tiezi:"3贴"
    //                             },
    //                             {
    //                                 tag:"虎扑knowing",
    //                                 tiezi:""
    //                             },
    //                             {
    //                                 tag:"世界篮球-FIBA",
    //                                 tiezi:"2贴"
    //                             }
    //                         ]
    //                     }
    //                 ]
    //             },
    //             {
    //                 brandTitle:"CBA论坛",
    //                 brandRow:[
    //                     {
    //                         brandRowTitle:"主版",
    //                         brandRowTag:[
    //                             {
    //                                 tag:"中国篮球",
    //                                 tiezi:"1561贴"
    //                             },
    //                             {
    //                                 tag:"中国篮球话题区",
    //                                 tiezi:"896贴"
    //                             }
    //                         ]
    //                     },
    //                     {
    //                         brandRowTitle:"CBA球队",
    //                         brandRowTag:[
    //                             {
    //                                 tag:"广东华南虎",
    //                                 tiezi:"3317贴"
    //                             },
    //                             {
    //                                 tag:"辽宁飞豹",
    //                                 tiezi:"2256贴"
    //                             },
    //                             {
    //                                 tag:"新疆飞虎",
    //                                 tiezi:"2357贴"
    //                             },
    //                             {
    //                                 tag:"上海大鲨鱼",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"山东金星",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"北京鸭",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"江苏龙",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"浙江广厦猛狮",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"山西猛龙",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"深圳烈豹",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"福建中华鲟",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"四川蓝鲸",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"八一火箭",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"吉林东北虎",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"浙江稠州金牛",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"广州龙狮",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"北京翱龙",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"青岛雄鹰",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"南京大圣",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"天津金狮",
    //                                 tiezi:"555贴"
    //                             }
    //                         ]
    //                     }
    //                 ]
    //             },
    //             {
    //                 brandTitle:"国际足球论坛",
    //                 brandRow:[
    //                     {
    //                         brandRowTitle:"主版",
    //                         brandRowTag:[
    //                             {
    //                                 tag:"足球话题区",
    //                                 tiezi:"1561贴"
    //                             },
    //                             {
    //                                 tag:"足球场",
    //                                 tiezi:"896贴"
    //                             },
    //                             {
    //                                 tag:"妖人银河系",
    //                                 tiezi:"23贴"
    //                             }
    //                         ]
    //                     },
    //                     {
    //                         brandRowTitle:"英超",
    //                         brandRowTag:[
    //                             {
    //                                 tag:"英超专区",
    //                                 tiezi:"3317贴"
    //                             },
    //                             {
    //                                 tag:"曼联专区",
    //                                 tiezi:"2256贴"
    //                             },
    //                             {
    //                                 tag:"阿森纳专区",
    //                                 tiezi:"2357贴"
    //                             },
    //                             {
    //                                 tag:"利物浦专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"切尔西专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"曼城专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"热刺专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"英冠专区",
    //                                 tiezi:"555贴"
    //                             }
    //                         ]
    //                     },
    //                     {
    //                         brandRowTitle:"西甲",
    //                         brandRowTag:[
    //                             {
    //                                 tag:"西甲专区",
    //                                 tiezi:"3317贴"
    //                             },
    //                             {
    //                                 tag:"皇马专区",
    //                                 tiezi:"2256贴"
    //                             },
    //                             {
    //                                 tag:"巴萨专区",
    //                                 tiezi:"2357贴"
    //                             },
    //                             {
    //                                 tag:"马竞专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"埃瓦尔官方专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"瓦伦西亚专区",
    //                                 tiezi:"555贴"
    //                             }
    //                         ]
    //                     },
    //                     {
    //                         brandRowTitle:"意甲",
    //                         brandRowTag:[
    //                             {
    //                                 tag:"意甲专区",
    //                                 tiezi:"3317贴"
    //                             },
    //                             {
    //                                 tag:"米兰专区",
    //                                 tiezi:"2256贴"
    //                             },
    //                             {
    //                                 tag:"国米专区",
    //                                 tiezi:"2357贴"
    //                             },
    //                             {
    //                                 tag:"尤文专区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"罗马专区",
    //                                 tiezi:"555贴"
    //                             }
    //                         ]
    //                     },
    //                     {
    //                         brandRowTitle:"法甲",
    //                         brandRowTag:[
    //                             {
    //                                 tag:"法兰西足球",
    //                                 tiezi:"3317贴"
    //                             },
    //                             {
    //                                 tag:"巴黎专区",
    //                                 tiezi:"2256贴"
    //                             }
    //                         ]
    //                     }
    //                 ]
    //             },
    //             {
    //                 brandTitle:"游戏电竞",
    //                 brandRow:[
    //                     {
    //                         brandRowTitle:"MOBA游戏",
    //                         brandRowTag:[
    //                             {
    //                                 tag:"英雄联盟",
    //                                 tiezi:"1561贴"
    //                             },
    //                             {
    //                                 tag:"DOTA 2",
    //                                 tiezi:"896贴"
    //                             },
    //                             {
    //                                 tag:"王者荣耀",
    //                                 tiezi:"223贴"
    //                             }
    //                         ]
    //                     },
    //                     {
    //                         brandRowTitle:"FPS游戏",
    //                         brandRowTag:[
    //                             {
    //                                 tag:"CS:GO",
    //                                 tiezi:"3317贴"
    //                             },
    //                             {
    //                                 tag:"绝地求生",
    //                                 tiezi:"2256贴"
    //                             },
    //                             {
    //                                 tag:"堡垒之夜",
    //                                 tiezi:"2357贴"
    //                             },
    //                             {
    //                                 tag:"守望先锋",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"刺激战场",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"彩虹六号：围攻",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"ROE(无限法则)",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"CF穿越火线手游",
    //                                 tiezi:"555贴"
    //                             }
    //                         ]
    //                     },
    //                     {
    //                         brandRowTitle:"综合类",
    //                         brandRowTag:[
    //                             {
    //                                 tag:"炉石传说",
    //                                 tiezi:"3317贴"
    //                             },
    //                             {
    //                                 tag:"Artifact专区",
    //                                 tiezi:"2256贴"
    //                             },
    //                             {
    //                                 tag:"文明Civilization",
    //                                 tiezi:"2357贴"
    //                             },
    //                             {
    //                                 tag:"FIFA19",
    //                                 tiezi:"555贴"
    //                             }
    //                         ]
    //                     },
    //                     {
    //                         brandRowTitle:"RPG游戏",
    //                         brandRowTag:[
    //                             {
    //                                 tag:"游戏区",
    //                                 tiezi:"3317贴"
    //                             },
    //                             {
    //                                 tag:"刺客信条专区",
    //                                 tiezi:"2256贴"
    //                             },
    //                             {
    //                                 tag:"巫师专区",
    //                                 tiezi:"2357贴"
    //                             },
    //                             {
    //                                 tag:"精灵宝可梦",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"十万种游戏死法",
    //                                 tiezi:"555贴"
    //                             }
    //                         ]
    //                     }
    //                 ]
    //             },
    //             {
    //                 brandTitle:"步行街",
    //                 brandRow:[
    //                     {
    //                         brandRowTitle:"步行街",
    //                         brandRowTag:[
    //                             {
    //                                 tag:"步行街主干道",
    //                                 tiezi:"1561贴"
    //                             }
    //                         ]
    //                     },
    //                     {
    //                         brandRowTitle:"影音娱乐",
    //                         brandRowTag:[
    //                             {
    //                                 tag:"娱乐圈",
    //                                 tiezi:"3317贴"
    //                             },
    //                             {
    //                                 tag:"影视区",
    //                                 tiezi:"2256贴"
    //                             },
    //                             {
    //                                 tag:"ACG区",
    //                                 tiezi:"2357贴"
    //                             },
    //                             {
    //                                 tag:"音乐区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"Steam新游推荐",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"手游推荐区",
    //                                 tiezi:"555贴"
    //                             }
    //                         ]
    //                     },
    //                     {
    //                         brandRowTitle:"图片视频",
    //                         brandRowTag:[
    //                             {
    //                                 tag:"爆照区",
    //                                 tiezi:"3317贴"
    //                             },
    //                             {
    //                                 tag:"什么图都有",
    //                                 tiezi:"2256贴"
    //                             },
    //                             {
    //                                 tag:"视频区",
    //                                 tiezi:"2357贴"
    //                             },
    //                             {
    //                                 tag:"手机壁纸区",
    //                                 tiezi:"555贴"
    //                             }
    //                         ]
    //                     },
    //                     {
    //                         brandRowTitle:"生活",
    //                         brandRowTag:[
    //                             {
    //                                 tag:"数码区",
    //                                 tiezi:"3317贴"
    //                             },
    //                             {
    //                                 tag:"家装房产",
    //                                 tiezi:"2256贴"
    //                             },
    //                             {
    //                                 tag:"股票区",
    //                                 tiezi:"2357贴"
    //                             },
    //                             {
    //                                 tag:"旅游区",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"车友交流",
    //                                 tiezi:"555贴"
    //                             }
    //                         ]
    //                     }
    //                 ]
    //             },
    //             {
    //                 brandTitle:"自建板块",
    //                 brandRow:[
    //                     {
    //                         brandRowTitle:"明星&人物",
    //                         brandRowTag:[
    //                             {
    //                                 tag:"创造101",
    //                                 tiezi:"1561贴"
    //                             },
    //                             {
    //                                 tag:"Ma酱馆",
    //                                 tiezi:"1561贴"
    //                             },
    //                             {
    //                                 tag:"SNH48",
    //                                 tiezi:"1561贴"
    //                             },
    //                             {
    //                                 tag:"新垣结衣",
    //                                 tiezi:"1561贴"
    //                             },
    //                             {
    //                                 tag:"迪丽热巴",
    //                                 tiezi:"1561贴"
    //                             },
    //                             {
    //                                 tag:"石原里美",
    //                                 tiezi:"1561贴"
    //                             },
    //                             {
    //                                 tag:"石川佳纯后援会",
    //                                 tiezi:"1561贴"
    //                             },
    //                             {
    //                                 tag:"陈奕迅专区",
    //                                 tiezi:"1561贴"
    //                             },
    //                             {
    //                                 tag:"周杰伦",
    //                                 tiezi:"1561贴"
    //                             }
    //                         ]
    //                     },
    //                     {
    //                         brandRowTitle:"兴趣圈",
    //                         brandRowTag:[
    //                             {
    //                                 tag:"留学专区",
    //                                 tiezi:"3317贴"
    //                             },
    //                             {
    //                                 tag:"权力的游戏",
    //                                 tiezi:"2256贴"
    //                             },
    //                             {
    //                                 tag:"DC",
    //                                 tiezi:"2357贴"
    //                             },
    //                             {
    //                                 tag:"小酒馆",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"虎扑三国",
    //                                 tiezi:"555贴"
    //                             },
    //                             {
    //                                 tag:"日剧",
    //                                 tiezi:"555贴"
    //                             }
    //                         ]
    //                     },
    //                     {
    //                         brandRowTitle:"游戏&娱乐",
    //                         brandRowTag:[
    //                             {
    //                                 tag:"圣斗士星矢手游",
    //                                 tiezi:"3317贴"
    //                             },
    //                             {
    //                                 tag:"FM专区",
    //                                 tiezi:"2256贴"
    //                             },
    //                             {
    //                                 tag:"魔兽世界",
    //                                 tiezi:"2357贴"
    //                             }
    //                         ]
    //                     },
    //                     {
    //                         brandRowTitle:"图片&视频",
    //                         brandRowTag:[
    //                             {
    //                                 tag:"猫猫和狗狗",
    //                                 tiezi:"3317贴"
    //                             }
    //                         ]
    //                     }
    //                 ]
    //             }
    //         ]
    //     }
    // }
}
</script>

<style scoped>
    body{
        height: 100%;
    }
</style>
